# Local deployment application.properties

controller.auth.admin.username=admin
controller.auth.admin.password=admin123

spring.datasource.url=jdbc:postgresql://postgres:5432/contigalias_db
spring.datasource.username=contigalias_user
spring.datasource.password=contigalias_password
spring.jpa.hibernate.ddl-auto=update

config.scaffolds.enabled=true
