/*
 * Copyright 2020 EMBL - European Bioinformatics Institute
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.ac.ebi.eva.contigalias.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.annotations.ApiModelProperty;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


@Entity
@Table(name = "chromosome")
public class ChromosomeEntity {

    @JsonIgnore
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(nullable = false)
    @ApiModelProperty(value = "Autogenerated Primary Key.")
    private long id;

    @ApiModelProperty(value = "The name of the chromosome.")
    private String name;

    @ApiModelProperty(value = "Chromosome's GenBank accession.")
    private String genbank;

    @ApiModelProperty(value = "Chromosome's RefSeq accession.")
    private String refseq;

    @ApiModelProperty(value = "Chromosome's UCSC style name")
    private String ucscName;

    @ApiModelProperty(value = "Chromosome's MD5 checksum value.")
    private String md5checksum;

    @ApiModelProperty(value = "Chromosome's TRUNC512 checksum value.")
    private String trunc512checksum;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @ApiModelProperty(value = "Assembly that this chromosome belongs to.")
    @ManyToOne(cascade = CascadeType.ALL)
    private AssemblyEntity assembly;

    public ChromosomeEntity() {
    }

    public long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public ChromosomeEntity setName(String name) {
        this.name = name;
        return this;
    }

    public String getGenbank() {
        return genbank;
    }

    public ChromosomeEntity setGenbank(String genbank) {
        this.genbank = genbank;
        return this;
    }

    public String getRefseq() {
        return refseq;
    }

    public ChromosomeEntity setRefseq(String refseq) {
        this.refseq = refseq;
        return this;
    }

    public String getUcscName() {
        return ucscName;
    }

    public ChromosomeEntity setUcscName(String ucscName) {
        this.ucscName = ucscName;
        return this;
    }

    public String getMd5checksum() {
        return md5checksum;
    }

    public ChromosomeEntity setMd5checksum(String md5checksum) {
        this.md5checksum = md5checksum;
        return this;
    }

    public String getTrunc512checksum() {
        return trunc512checksum;
    }

    public ChromosomeEntity setTrunc512checksum(String trunc512checksum) {
        this.trunc512checksum = trunc512checksum;
        return this;
    }

    public AssemblyEntity getAssembly() {
        return assembly;
    }

    public ChromosomeEntity setAssembly(AssemblyEntity assembly) {
        this.assembly = assembly;
        return this;
    }

    @Override
    public String toString() {
        return "ChromosomeEntity{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", genbank='" + genbank + '\'' +
                ", refseq='" + refseq + '\'' +
                ", ucscName='" + ucscName + '\'' +
                ", md5checksum='" + md5checksum + '\'' +
                ", trunc512checksum='" + trunc512checksum + '\'' +
                ", assembly=" + assembly +
                '}';
    }
}
