/*
 * Copyright 2020 EMBL - European Bioinformatics Institute
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.ac.ebi.eva.contigalias.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.annotations.ApiModelProperty;
import org.springframework.boot.autoconfigure.condition.ConditionalOnBean;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

@Entity
@Table(name = "scaffold")
public class ScaffoldEntity {

    @JsonIgnore
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(nullable = false)
    @ApiModelProperty(value = "Autogenerated Primary Key.")
    private long id;

    @ApiModelProperty(value = "The name of the scaffold.")
    private String name;

    @ApiModelProperty(value = "Scaffold's Genbank accession.")
    private String genbank;

    @ApiModelProperty(value = "Scaffold's Refseq accession.")
    private String refseq;

    @ApiModelProperty(value = "The UCSC name of the  scaffold.")
    private String ucscName;

    @JsonInclude(JsonInclude.Include.NON_NULL)
    @ApiModelProperty(value = "Assembly that this scaffold belongs to.")
    @ManyToOne(cascade = CascadeType.ALL)
    private AssemblyEntity assembly;

    public ScaffoldEntity() {
    }

    public long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public ScaffoldEntity setName(String name) {
        this.name = name;
        return this;
    }

    public String getGenbank() {
        return genbank;
    }

    public ScaffoldEntity setGenbank(String genbank) {
        this.genbank = genbank;
        return this;
    }

    public String getRefseq() {
        return refseq;
    }

    public ScaffoldEntity setRefseq(String refseq) {
        this.refseq = refseq;
        return this;
    }

    public String getUcscName() {
        return ucscName;
    }

    public ScaffoldEntity setUcscName(String ucscName) {
        this.ucscName = ucscName;
        return this;
    }

    public AssemblyEntity getAssembly() {
        return assembly;
    }

    public ScaffoldEntity setAssembly(AssemblyEntity assembly) {
        this.assembly = assembly;
        return this;
    }

}
